version: '3.8'

services:
  mongodb:
    image: mongo:7.0.8
    env_file: .env
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command:
      mongod --quiet --logpath /dev/null
    volumes:
      - ./data:/data/db
      
  api:
    build: 
      context: .
      dockerfile: ./guard-api/Dockerfile
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    command:  sh -c "uvicorn guard-api.main:app  --port=8000 --host=0.0.0.0 --reload"
 

  