FROM python:3.9

# 
WORKDIR /code

# 
COPY ./guard-api/requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./ /code/

# 
# CMD ["fastapi", "run", "app/main.py", "--port", "80"]